# docker compose run --rm dotfiles_test
services:
  dotfiles_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
    volumes:
      - .:/home/${USER}/dotfiles_repository # Mount the repo folder to to a home folder in the container
