# Most of these are taken directly from https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh

alias ga "git add"
alias gaa "git add --all"
alias gapa "git add --patch"
alias gau "git add --update"
alias gwip "git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message \"--wip-- [skip ci]\""
alias gap "git apply"
alias gb "git branch"
alias gbr "git branch --remote"
alias gco "git checkout"
alias gcor "git checkout --recurse-submodules"
alias gcb "git checkout -b"
alias gcB "git checkout -B"
alias gcd "git checkout (git_develop_branch)"
alias gcm "git checkout (git_main_branch)"
alias gcp "git cherry-pick"
alias gcpa "git cherry-pick --abort"
alias gcpc "git cherry-pick --continue"
alias gclean "git clean --interactive -d"
alias gcl "git clone --recurse-submodules"
alias gc "git commit --verbose"
alias gca "git commit --verbose --all"
alias gca! "git commit --verbose --all --amend"
alias gcan! "git commit --verbose --all --no-edit --amend"
alias gc! "git commit --verbose --amend"
alias gcf "git config --list"
alias gcfu "git commit --fixup"
alias gd "git diff"
alias gdca "git diff --cached"
alias gdcw "git diff --cached --word-diff"
alias gds "git diff --staged"
alias gdw "git diff --word-diff"
alias gfo "git fetch origin"
alias gm "git merge"
alias gma "git merge --abort"
alias gmc "git merge --continue"
alias gms "git merge --squash"
alias gmff "git merge --ff-only"
alias gl "git pull"
alias gp "git push"
alias gpd "git push --dry-run"
alias grb "git rebase"
alias grba "git rebase --abort"
alias grbc "git rebase --continue"
alias grbi "git rebase --interactive"
alias grbo "git rebase --onto"
alias grbs "git rebase --skip"
alias grh "git reset"
alias gru "git reset --"
alias grhh "git reset --hard"
alias grhk "git reset --keep"
alias grhs "git reset --soft"
alias gwipe "git reset --hard && git clean --force -df"
alias groh "git reset origin/(git_current_branch) --hard"
alias grs "git restore"
alias grss "git restore --source"
alias grst "git restore --staged"
alias gunwip "git rev-list --max-count 1 --format "%s" HEAD | grep -q "\--wip--" && git reset HEAD~1"
alias grev "git revert"
alias greva "git revert --abort"
alias grevc "git revert --continue"
alias grm "git rm"
alias gstall "git stash --all"
alias gstaa "git stash apply"
alias gstc "git stash clear"
alias gstd "git stash drop"
alias gstl "git stash list"
alias gstp "git stash pop"
alias gsi "git submodule init"
alias gsu "git submodule update"
alias gsw "git switch"
alias gswc "git switch --create"
alias gswd "git switch (git_develop_branch)"
alias gswm "git switch (git_main_branch)"
