# Dropping to the shell
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

# Smart paste: paste files without entering the directory
[[mgr.prepend_keymap]]
on   = "P"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

# Smart tab: create a tab and enter the hovered directory
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

# Merge this into one command for wayland and X11
# [[manager.prepend_keymap]]
# on  = "y"
# run = [ '''
# 	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list'
# ''', "yank" ]

# [[manager.prepend_keymap]]
# on  = "y"
# run = [ '''
# 	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
# ''', "yank" ]

# cd back to the root of the current Git repository
[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''

# TODO write plugin for better preview
[[mgr.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'sushi "$@"'
'''
