# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

right_format = """$time"""


[line_break]
disabled = true

[time]
disabled = false


[python]
version_format = "v${major}.${minor}"
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = "\ue73c " # 

[rust]
# format = "[( )]()"
symbol = "\ue7a8 " # 
